Use IMAGE_DIGEST in OLM template
openshift/route-monitor-operator pull request #113
Opened 2021-05-13 21:42 UTC by 2uasimojo

To make the OLM template easier to understand, replace `${REPO_DIGEST}` with `${REGISTRY_IMG}@${IMAGE_DIGEST}`.

`IMAGE_DIGEST` is supported as of APPSRE-3265.

2021-05-14 06:23 UTC, NautiluX commented
@2uasimojo this PR doesn't change anything, is it missing something or can we close it?

2021-05-14 06:24 UTC, NautiluX requested changes
@2uasimojo this PR doesn't change anything, is it missing something or can we close it?

2021-05-14 07:26 UTC, 2uasimojo commented
Yeesh. I did 15 of these in a row, inevitable that I would mess up at least one.

There should definitely be a delta. Leave it with me. 

/hold

2021-05-14 14:50 UTC, 2uasimojo commented
> There should definitely be a delta. Leave it with me.

Fixed.

/hold cancel

2021-05-17 14:23 UTC, NautiluX reviewed
/lgtm

2021-05-17 15:55 UTC, merged