api-ErrorBudgetBurn fires before cluster api is Ready
openshift/route-monitor-operator pull request #208
Opened 2023-06-16 19:32 UTC by anispate

2023-06-16 20:12 UTC, sam-nguyen7 requested changes
@anispate Please help add a description for this PR as well. Thanks!

2023-06-16 20:12 UTC, sam-nguyen7 commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +func (s *ClusterUrlMonitorReconciler) FindStatusCondition(conditions []metav1.Condition, conditionType string) *metav1.Condition {
Are there any benefits to have our own implementation of FindStatusCondition as opposed to using https://pkg.go.dev/k8s.io/apimachinery/pkg/api/meta#FindStatusCondition?

2023-06-16 20:12 UTC, sam-nguyen7 commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +func (s *ClusterUrlMonitorReconciler) FindStatusCondition(conditions []metav1.Condition, conditionType string) *metav1.Condition {
We can simplify this logic by having one helper function determine if cluster is available (eg. https://github.com/openshift/hypershift/pull/2147/files#diff-3d4ffda0834e09a59a4d510523932e20b9234bcb9816e40258a0fb32a87a7006R187) then requeue when !isClusterVersionAvailable

2023-06-16 20:12 UTC, sam-nguyen7 commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +	condition, err := s.FindStatusCondition(hcp.Status.Conditions, string(metav1.ClusterVersionAvailable))
`FindStatusCondition` returns `*metav1.Condition`, but here you're expecting `condition, err`

2023-06-16 20:26 UTC, fahlmant commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +	}
What does this block do?

2023-06-16 20:27 UTC, fahlmant commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +		return utilreconcile.RequeueReconcileWith(err)
What's the expected err to return here?

2023-06-16 20:27 UTC, fahlmant commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +		return utilreconcile.RequeueReconcileWith(err)
What's the expected err to return here?

2023-06-16 20:32 UTC, fahlmant commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +	}
```suggestion
	for _,condition := range conditions {
		if condition.Type == conditionType {
			return &condition
		}
	}
```

2023-06-16 21:40 UTC, fahlmant commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +	if condition.Status = nil  {
```suggestion
	if condition.Status == nil  {
```

2023-06-20 15:59 UTC, fahlmant commented on controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
> +			return utilreconcile.RequeueReconcileWith(err)
Wouldn't the `err` be nil here?

2023-06-23 15:38 UTC, fahlmant commented
@anispate can you update the description to explain what the code change you're making does and how it fixes the issue?

2023-07-13 19:35 UTC, mjlshen reviewed
/lgtm

2023-07-14 14:44 UTC, sam-nguyen7 reviewed
/approve

2023-07-14 17:58 UTC, sam-nguyen7 commented
/approve

2023-07-14 18:27 UTC, merged